### ISSUE TITLE
thirdpartylibs.xml should be present

### ISSUE THREAD

**Issue by mudrd8mz** [tigusigalpa/moodle_admin_tool_imageoptimize#1]
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml should be present to declare all the third party libraries shipping with the plugin, and their licences.

**Comment by tigusigalpa** [comment]
done :)

**Comment by mudrd8mz** [comment]
Thank you. Ideally, all the pulled-in dependencies such as vendor/symfony/process/ should be declared too. But this is a good start for sure.

**Comment by tigusigalpa** [comment]
yes, i did it https://github.com/tigusigalpa/moodle_admin_tool_imageoptimize/blob/master/thirdpartylibs.xml
