### ISSUE TITLE
Tool removing images

### ISSUE THREAD

**Issue by rschrenk** [tigusigalpa/moodle_admin_tool_imageoptimize#10]
Hello,

we recently installed your tool after testing it on our development server, where everything seemed fine. In our production system, many images are lost since we activated it there. 

I checked your code (https://github.com/tigusigalpa/moodle-tool_imageoptimize/blob/62e23d51d8d87b0842a2929c0bd2dee5da921d73/tool_imageoptimize.php#L344) and it seems that what you do is the following:
1. Get current picture file, path and create temporary file
2. If the temporary file exists do the rest:
3. Optimize image
4. create new content- and pathnamehash
5. UPDATE file record ($this->db->update_record('files', $this->filerecord);)
6. Remove temporary files and the old file

In Step 5 the update is done by moodle using the primary key (id) of the filerecord, but many other images using the same contenthash may exist.

Is it possible, that you are making all other instances of this file entry invalid except the one you are updating? 

**Before you remove the original file, you _must_ ensure, that it is not used any more by any other record of the files table!**

Kind regards

**Comment by tigusigalpa** [comment]
Hi Robert!
Uh, i am so sorry, i will review it next days. Thanks.

**Comment by PM84** [comment]
I contributed a big extension, that should also solve this issue. #13

**Comment by tigusigalpa** [comment]
> I contributed a big extension, that should also solve this issue. #13

Thanks a lot for your great job!!!
