### ISSUE TITLE
The plugin description in the plugins directory could be improved

### ISSUE THREAD

**Issue by mudrd8mz** [tigusigalpa/moodle_admin_tool_imageoptimize#4]
Not all admins read the README files so it generally advised to keep the information in README in sync with the plugin description at moodle.org/plugins. Currently the text there reads just "Save your hard disk size by optimizing/compressing images on a fly with Moodle based hooks." But it would deserve more information - what it does, why it does it, how it does it etc. Better when users are well informed about he plugin's features and behaviour before installing it.

**Comment by tigusigalpa** [comment]
Updated with https://github.com/tigusigalpa/moodle_admin_tool_imageoptimize/commit/1ad9dee91605ee8df238f65165b2c59dc024c623
