### ISSUE TITLE
$settingsShow gets false but never back to true

### ISSUE THREAD

**Issue by mudrd8mz** [tigusigalpa/moodle_admin_tool_imageoptimize#5]
Out of all the OS packages, let's have only the `optipng` installed. As far as I can see, it should be enough to make the optimisation work for PNG files. But because of all the extra logic in the settings.php regarding the the `$settingsShow` the section with the "create", "update" and "more_than" is not shown (as the JPG failed OS check makes it hidden). 

As a result, there is no way to configure it to work for PNGs.

**Comment by mudrd8mz** [comment]
Let me suggest to not hide that section. No reason for that.

**Comment by tigusigalpa** [comment]
well, i done that with https://github.com/tigusigalpa/moodle_admin_tool_imageoptimize/commit/9576e36e4ff162a59638aaa523405077c94eeeb5 and https://github.com/tigusigalpa/moodle_admin_tool_imageoptimize/commit/3fa91213da617556dc38b0b795748a679c8b161f
but maybe pngQuant is the best for PNG, i don't know =)
