### ISSUE TITLE
unlink() should not be used to remove (potentially non-empty) directories

### ISSUE THREAD

**Issue by mudrd8mz** [tigusigalpa/moodle_admin_tool_imageoptimize#6]
When uninstalling the plugin:

PHP Warning:  unlink(moodledata/temp/tool_imageoptimize): Is a directory in admin/tool/imageoptimize/db/uninstall.php on line 31

**Comment by tigusigalpa** [comment]
Sorry David, you're absolutely right.. Fixed https://github.com/tigusigalpa/moodle_admin_tool_imageoptimize/commit/28d6ed8911c70b86493086a9798a8acb3d064dd8
