### ISSUE TITLE
Consider renaming this repo to moodle-tool_imageoptimize

### ISSUE THREAD

**Issue by brendanheywood** [tigusigalpa/moodle_admin_tool_imageoptimize#7]
There is a de facto convention that plugins are named like this:

https://github.com/tigusigalpa/moodle-tool_imageoptimize

Before it gets widespread attention is the best time to do it, - and btw this plugin looks awesome :)

**Comment by tigusigalpa** [comment]
Hi Brendan! Thanks a lot for a good words!!! thanks a lot! yes, i have renamed the repo
